services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: infocom-backend
        ports:
            - "8080:8080"
        restart: always

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: infocom-frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        restart: always
